config/routes.rb
Rails.application.routes.draw do

  scope 'dashboard' do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :mosques, only: [:index]
    resources :users, except: [:new, :create, :update, :edit, :destroy] do
      resources :mosques, path: 'mosque', except: [:create, :index] do
        
      end
      post 'mosque', to: 'mosques#create', as: :create_mosque
      patch 'mosque', to: 'mosques#create'
    end

  end

  devise_for :users, controllers: { 
    :sessions             => 'users/sessions',
    :registrations        => 'users/registrations',
    # :omniauth_callbacks => "users/omniauth_callbacks" ,
    :invitations          => 'users/invitations',
    :confirmations        => 'users/confirmations',
    :passwords            => 'users/passwords'
  }
  
  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'pages/index'
  root 'pages#index'
  
  namespace :api do
    namespace :v1, defaults: { format: :json } do
      get 'prayer-times/:duration', to: 'prayer_times#index'
      get 'mosques', to: 'mosques#index'
      mount_devise_token_auth_for 'User', at: 'users', controllers: {
        registrations:  'api/v1/registrations',   as: :new_user_api_registration,
        sessions:       'api/v1/sessions',        as: :user_api_session,
        passwords:      'api/v1/passwords',       as: :new_user_api_password
      }
      devise_scope :user do
        get :status, to: 'api#status'
        resources :users, only: :show
        resource :user, only: :update do
          get :profile
        end
      end
    end
  end
  
end

app/models/mosque.rb
# == Schema Information
#
# Table name: mosques
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  address    :text
#  latitude   :float
#  longitude  :float
#  user_id    :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#  city       :string
#  zipcode    :string
#  country    :string
#  iqomah     :integer
#

class Mosque < ApplicationRecord
	extend FriendlyId
	is_impressionable
  friendly_id :name, use: :slugged
  mount_uploader :avatar, AvatarUploader

  belongs_to :user

  accepts_nested_attributes_for :user

  validates :latitude, :longitude, :name, :country,  presence: true
  
end

app/controllers/api/v1/mosques_controller.rb
# encoding: utf-8
module Api
  module V1
    class MosquesController < ApplicationController

      def index
        render json: Mosque.all
      end
      
    end
  end
end

app/controllers/mosques_controller.rb
class MosquesController < InheritedResources::Base
	before_action :authenticate_user!
  before_action :set_user_mosque, only: [:show, :edit, :update, :destroy, :user_mosque]
  impressionist :actions=> [:show]


	def index
    @mosques = Mosque.all
    @mosque_count = Mosque.count
    @users_count = User.count
  end

  def user_mosque
    
  end

 
  def show
    impressionist(@mosque)
  end

  
  def new
    @mosque = Mosque.new
  end

  
  def edit
  end

  
  def create
    @mosque = current_user.create_mosque(mosque_params)

    respond_to do |format|
      if @mosque.save
        format.html { redirect_to user_mosque_path(current_user, @mosque), notice: 'Mosque was successfully created.' }
        format.json { render :show, status: :created, location: @mosque }
      else
        format.html { render :new }
        format.json { render json: @mosque.errors, status: :unprocessable_entity }
      end
    end
  end

  
  
  def update
    respond_to do |format|
      if @mosque.update(mosque_params)
        format.html { redirect_to user_mosque_path(current_user), notice: 'Mosque was successfully updated.' }
        format.json { render :show, status: :ok, location: @mosque }
      else
        format.html { render :edit }
        format.json { render json: @mosque.errors, status: :unprocessable_entity }
      end
    end
  end

  # def destroy
  #   @mosque.destroy
  #   respond_to do |format|
  #     format.html { redirect_to user_mosque_path(current_user), notice: 'Mosque was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private

    def mosque_params
      params.require(:mosque).permit(:name, :address, :latitude, :longitude, :user_id, :country, :city, :zipcode, :avatar)
    end

    def set_user_mosque
      @mosque = Mosque.friendly.find(params[:id])
    end
end

app/helpers/mosques_helper.rb
module MosquesHelper
end

app/views/mosques/_form.html.slim
= form_for(@mosque, :html => { class: 'form-horizontal', role: 'form' }, url: user_create_mosque_path(current_user)) do |f| 
  h6.heading-small.text-muted.mb-4 Mosque information
  .pl-lg-4
    .row
      .col-lg-6
        .form-group
          label.form-control-label for="mosque_name"  Name of mosque
          = f.text_field :name, class: "form-control form-control-alternative", placeholder: "Name of mosque", required: true
      .col-lg-6
        .form-group
          label.form-control-label for="mosque_contry"  Country
          = f.country_select('country', { include_blank: 'Select a country', selected: "ID" }, { class: "form-control select-select form-control-alternative", data: { attribute: "value" }})
          
    .row
      .col-lg-12
        .form-group
          label.form-control-label for="mosque_address"  Address
          = f.text_field :address, class: "form-control form-control-alternative", placeholder: "Address", required: true, onFocus: "geolocate();"
    .row
      .col-lg-6
        .form-group
          label.form-control-label for="mosque_latitude"  Latitude
          = f.text_field :latitude, class: "form-control form-control-alternative", placeholder: "Latitude", required: true
      .col-lg-6
        .form-group
          label.form-control-label for="mosque_latitude"  Longitude
          = f.text_field :longitude, class: "form-control form-control-alternative", placeholder: "Longitude", required: true
    .row
      .col-lg-6
        .form-group
          label.form-control-label for="mosque_city"  City
          = f.text_field :city, class: "form-control form-control-alternative", placeholder: "City", required: true
      .col-lg-6
        .form-group
          label.form-control-label for="mosque_zipcode"  Zipcode
          = f.text_field :zipcode, class: "form-control form-control-alternative", placeholder: "Zipcode", required: true
    .row
      .col-lg-6
        .form-group
          label.form-control-label for="mosque_avatar"  Mosque Picture
          = f.file_field :avatar, class: "form-control form-control-file", placeholder: "Mosque Picture"
    
          /= f.country_select("user", "country", { priority_countries: ["GB", "FR"], selected: "GB" }, { class: 'form-control', data: { attribute: "value" } })
          / = f.text_field :latitude, class: "form-control form-control-alternative", placeholder: "Latitude", required: true
      /.col-lg-6
        .form-group
          label.form-control-label for="mosque_zipcode"  Zipcode
          = f.text_field :zipcode, class: "form-control form-control-alternative", placeholder: "Zipcode", required: true
  hr.my-4/
  .pull-right
  	= f.submit 'Create', class: 'btn btn-info my-4 btn-submit', data: {loading_text: 'Creating...', disable_with: 'Please wait....'}

app/views/mosques/edit.html.slim
- model_class = Mosque
div class="page-header"
  h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

app/views/mosques/index.html.slim
- set_meta_tags title: 'listing All Mosque in Siforlat',
                description: 'listing All Mosque in Siforlat -  Sistem Informasi Jadwal Sholat - Siforlat merupakan aplikasi untuk menampilkan jadwal sholat secara realtime, informasi kajian, jadawal imam dan khotib, video kajian, dan informasi masjid lainya.',
                keywords: 'Sistem Informasi Jadwal Sholat, jadwal sholat, prayer times, aplikasi jadwal sholat, Sistem Informasi masjid',
                author: 'Siforlat',
                image: 'https://res.cloudinary.com/muhammadyana/image/upload/v1543910639/siforlat/siforlat-thumbnail.jpg'
-content_for :meta_tags
  meta content="https://res.cloudinary.com/muhammadyana/image/upload/v1543910639/siforlat/siforlat-thumbnail.jpg" property="og:image" /

/ header 
.header.bg-gradient-info.pb-8.pt-5.pt-md-8
  .container-fluid
    .header-body
      /! Card stats
      .row
        .col-xl-4.col-lg-6.ml-auto
          .card.card-stats.mb-4.mb-xl-0
            .card-body
              .row
                .col
                  h5.card-title.text-uppercase.text-muted.mb-0 Registered All Mosque
                  span.h2.font-weight-bold.mb-0.imsak = @mosque_count
                .col-auto
                  .icon.icon-shape.bg-success.text-white.rounded-circle.shadow
                    i.ni.ni-istanbul
              p.mt-3.mb-0.text-muted.text-sm
                / span.text-success.mr-2
                  i.fa.fa-arrow-up
                  | 3.48%
                / span.text-nowrap Since last month
        .col-xl-4.col-lg-6.mr-auto
          .card.card-stats.mb-4.mb-xl-0
            .card-body
              .row
                .col
                  h5.card-title.text-uppercase.text-muted.mb-0 Registered All Users
                  span.h2.font-weight-bold.mb-0.imsak = @users_count
                .col-auto
                  .icon.icon-shape.bg-yellow.text-white.rounded-circle.shadow
                    i.fas.fa-users
              p.mt-3.mb-0.text-muted.text-sm
                / span.text-success.mr-2
                  i.fa.fa-arrow-up
                  | 3.48%
                / span.text-nowrap Since last month
.container-fluid.mt--7
  .row
    .col
      .card.shadow.border-0
        #map-canvas.map-canvas data-lat="-6.8970235" data-lng="107.6235107" style=("height: 600px;") 

- content_for :js_plugin
  script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAgPpgOeWedR2DXbnJYcg0hI9rFGVJQ5dw"
  = javascript_include_tag 'mosques'
        

    

app/views/mosques/new.html.slim
- set_meta_tags title: 'Register New Mosque',
                description: 'Register New Mosque -  Sistem Informasi Jadwal Sholat - Siforlat merupakan aplikasi untuk menampilkan jadwal sholat secara realtime, informasi kajian, jadawal imam dan khotib, video kajian, dan informasi masjid lainya.',
                keywords: 'Sistem Informasi Jadwal Sholat, jadwal sholat, prayer times, aplikasi jadwal sholat, Sistem Informasi masjid',
                author: 'Siforlat',
                image: 'https://res.cloudinary.com/muhammadyana/image/upload/v1543910639/siforlat/siforlat-thumbnail.jpg'
-content_for :meta_tags
  meta content="https://res.cloudinary.com/muhammadyana/image/upload/v1543910639/siforlat/siforlat-thumbnail.jpg" property="og:image" /
/ .header.bg-gradient-info.pb-8.pt-5.pt-md-8
/   .container-fluid
/     .header-body
/ - content_for :custom_library
	link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"
	script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"
.header.bg-gradient-info.pb-8.pt-5.pt-md-8
  /! Mask
  / span.mask.bg-gradient-default.opacity-8
  /! Header container
  .container-fluid.d-flex.align-items-center
    .row
      /.col-lg-7.col-md-10
        h1.display-2.text-white Hello Jesse
        p.text-white.mt-0.mb-5 This is your profile page. You can see the progress you've made with your work and manage your projects or assigned tasks
        a.btn.btn-info href="#!"  Edit profile
.container-fluid.mt--7
	.row
		.col-lg-12
		  .card.bg-secondary.shadow
		    .card-header.bg-white.border-0
		      .row.align-items-center
		        .col-8
		          h3.mb-0 Register New Mosque
		        / .col-4.text-right
		          a.btn.btn-sm.btn-primary href="#!"  Settings
		    .card-body
					.alert.alert-warning.alert-dismissible.fade.show role="alert" 
						strong Please allow browser to get your current location
					- if @mosque.errors.any?
						.alert.alert-danger.alert-dismissible.fade.show role="alert" 
							strong = pluralize(@mosque.errors.count, "Error")
							ul 
								-@mosque.errors.full_messages.each do |message|
									li = message
					= render partial: "form"	

- content_for :js_plugin
	
	javascript:
		var placeSearch, autocomplete;

		function initAutocomplete() {
			autocomplete = new google.maps.places.Autocomplete(
				(document.getElementById('mosque_address')),{types: ['geocode']
			});      
			autocomplete.addListener('place_changed', fillInAddress);
		}

		function fillInAddress() {
			var place = autocomplete.getPlace();
			$('#mosque_latitude').val(place.geometry.location.lat());
			$('#mosque_longitude').val(place.geometry.location.lng());
			for (var i = 0; i < place.address_components.length; i++) {
				for (var j = 0; j < place.address_components[i].types.length; j++) {
					if (place.address_components[i].types[j] == "administrative_area_level_2") {
						$('#mosque_city').val(place.address_components[i].long_name);
					}
					if (place.address_components[i].types[j] == "postal_code") {
						console.log(place.address_components[i].long_name);
						$('#mosque_zipcode').val(place.address_components[i].long_name);
					}
				}
			}
		}

		function geolocate() {
			if (navigator.geolocation) {
				navigator.geolocation.getCurrentPosition(function(position) {
					var geolocation = {
						lat: position.coords.latitude,
						lng: position.coords.longitude
					};
					var circle = new google.maps.Circle({
						center: geolocation,
						radius: position.coords.accuracy
					});
					autocomplete.setBounds(circle.getBounds());
				});
			}
		}
	script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAgPpgOeWedR2DXbnJYcg0hI9rFGVJQ5dw&libraries=places&callback=initAutocomplete"

app/views/mosques/show.html.slim
- set_meta_tags title: "#{current_user.full_name} - #{current_user.mosque.name}",
                description: 'listing All Mosque in Siforlat -  Sistem Informasi Jadwal Sholat - Siforlat merupakan aplikasi untuk menampilkan jadwal sholat secara realtime, informasi kajian, jadawal imam dan khotib, video kajian, dan informasi masjid lainya.',
                keywords: 'Sistem Informasi Jadwal Sholat, jadwal sholat, prayer times, aplikasi jadwal sholat, Sistem Informasi masjid',
                author: 'Siforlat',
                image: 'https://res.cloudinary.com/muhammadyana/image/upload/v1543910639/siforlat/siforlat-thumbnail.jpg'
-content_for :meta_tags
  meta content="https://res.cloudinary.com/muhammadyana/image/upload/v1543910639/siforlat/siforlat-thumbnail.jpg" property="og:image" /
- model_class = Mosque
/ div class="page-header"
  h1=t '.title', default: model_class.model_name.human.titleize
.header.pb-8.pt-5.pt-lg-8.d-flex.align-items-center style=("min-height: 600px; background-image: url(#{@mosque.avatar.cover.url}); background-size: cover; background-position: center top;") 
  /! Mask
  span.mask.bg-gradient-default.opacity-8
  /! Header container
  .container-fluid.d-flex.align-items-center
    .row
      .col-lg-10.col-md-10
        h1.display-2.text-white = @mosque.name
        p.text-white.mt-0.mb-5 = @mosque.address
        a.btn.btn-info href="#!"  Edit Mosque

.container-fluid.mt--7
  .row
    .col-xl-4.order-xl-2.mb-5.mb-xl-0
      .card.card-profile.shadow
        .row.justify-content-center
          .col-lg-3.order-lg-2
            .card-profile-image
              a href="#" 
                = image_tag @mosque.avatar.url, class: "rounded-circle"
        .card-header.text-center.border-0.pt-8.pt-md-4.pb-0.pb-md-4
          / .d-flex.justify-content-between
            a.btn.btn-sm.btn-info.mr-4 href="#"  Connect
            a.btn.btn-sm.btn-default.float-right href="#"  Message
        .card-body.pt-0.pt-md-4
          .row
            .col
              .card-profile-stats.d-flex.justify-content-center.mt-md-5
                div
                  span.heading = @mosque.impressionist_count
                  span.description Views
                /div
                  span.heading 10
                  span.description Photos
                /div
                  span.heading 89
                  span.description Comments
          .text-center
            h3
              = @mosque.name
              / span.font-weight-light , 27
            .h5.font-weight-300
              i.ni.location_pin.mr-2
              = @mosque.address
            /.h5.mt-4
              i.ni.business_briefcase-24.mr-2
              | Solution Manager - Creative Tim Officer
            /div
              i.ni.education_hat.mr-2
              | University of Computer Science
            hr.my-4/
            / p Ryan — the name taken by Melbourne-raised, Brooklyn-based Nick Murphy — writes, performs and records all of his own music.
            / a href="#"  Show more
    /.col-xl-8.order-xl-1
      .card.bg-secondary.shadow
        .card-header.bg-white.border-0
          .row.align-items-center
            .col-8
              h3.mb-0 My account
            .col-4.text-right
              a.btn.btn-sm.btn-primary href="#!"  Settings
        .card-body
          form
            h6.heading-small.text-muted.mb-4 User information
            .pl-lg-4
              .row
                .col-lg-6
                  .form-group
                    label.form-control-label for="input-username"  Username
                    input#input-username.form-control.form-control-alternative placeholder="Username" type="text" value="lucky.jesse" /
                .col-lg-6
                  .form-group
                    label.form-control-label for="input-email"  Email address
                    input#input-email.form-control.form-control-alternative placeholder="jesse@example.com" type="email" /
              .row
                .col-lg-6
                  .form-group
                    label.form-control-label for="input-first-name"  First name
                    input#input-first-name.form-control.form-control-alternative placeholder=("First name") type="text" value="Lucky" /
                .col-lg-6
                  .form-group
                    label.form-control-label for="input-last-name"  Last name
                    input#input-last-name.form-control.form-control-alternative placeholder=("Last name") type="text" value="Jesse" /
            hr.my-4/
            /! Address
            h6.heading-small.text-muted.mb-4 Contact information
            .pl-lg-4
              .row
                .col-md-12
                  .form-group
                    label.form-control-label for="input-address"  Address
                    input#input-address.form-control.form-control-alternative placeholder=("Home Address") type="text" value="Bld Mihail Kogalniceanu, nr. 8 Bl 1, Sc 1, Ap 09" /
              .row
                .col-lg-4
                  .form-group
                    label.form-control-label for="input-city"  City
                    input#input-city.form-control.form-control-alternative placeholder="City" type="text" value=("New York") /
                .col-lg-4
                  .form-group
                    label.form-control-label for="input-country"  Country
                    input#input-country.form-control.form-control-alternative placeholder="Country" type="text" value=("United States") /
                .col-lg-4
                  .form-group
                    label.form-control-label for="input-country"  Postal code
                    input#input-postal-code.form-control.form-control-alternative placeholder=("Postal code") type="number" /
            hr.my-4/
            /! Description
            h6.heading-small.text-muted.mb-4 About me
            .pl-lg-4
              .form-group
                label About Me
                textarea.form-control.form-control-alternative placeholder=("A few words about you ...") rows="4"  A beautiful Dashboard for Bootstrap 4. It is Free and Open Source.


/ .fieldset
  dl
      dt.label.label-default= model_class.human_attribute_name(:name)
      dd
        pre.prettyprint= @mosque.name
      dt.label.label-default= model_class.human_attribute_name(:address)
      dd
        pre.prettyprint= @mosque.address
      dt.label.label-default= model_class.human_attribute_name(:latitude)
      dd
        pre.prettyprint= @mosque.latitude
      dt.label.label-default= model_class.human_attribute_name(:longitude)
      dd
        pre.prettyprint= @mosque.longitude
      dt.label.label-default= model_class.human_attribute_name(:user_id)
      dd
        pre.prettyprint= @mosque.user_id

/ .form-group
  = link_to t('.back', default: t("helpers.links.back")), mosques_path, class: 'btn btn-default'
  '
  = link_to t('.edit', default: t("helpers.links.edit")), edit_user_mosque_path(current_user, @mosque), class: 'btn btn-default'
  '
  /= link_to t('.destroy', default: t("helpers.links.destroy")), mosque_path(@mosque), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'