config/routes.rb
Rails.application.routes.draw do

  scope 'dashboard' do
    get '/', to: 'dashboard#index', as: :dashboard
    resources :mosques, only: [:index]
    resources :users, except: [:new, :create, :update, :edit, :destroy] do
      resources :mosques, path: 'mosque', except: [:create, :index] do
        
      end
      post 'mosque', to: 'mosques#create', as: :create_mosque
      patch 'mosque', to: 'mosques#create'
    end

  end

  devise_for :users, controllers: { 
    :sessions             => 'users/sessions',
    :registrations        => 'users/registrations',
    # :omniauth_callbacks => "users/omniauth_callbacks" ,
    :invitations          => 'users/invitations',
    :confirmations        => 'users/confirmations',
    :passwords            => 'users/passwords'
  }
  
  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy'
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'pages/index'
  root 'pages#index'
  
  namespace :api do
    namespace :v1, defaults: { format: :json } do
      get 'prayer-times/:duration', to: 'prayer_times#index'
      get 'mosques', to: 'mosques#index'
      mount_devise_token_auth_for 'User', at: 'users', controllers: {
        registrations:  'api/v1/registrations',   as: :new_user_api_registration,
        sessions:       'api/v1/sessions',        as: :user_api_session,
        passwords:      'api/v1/passwords',       as: :new_user_api_password
      }
      devise_scope :user do
        get :status, to: 'api#status'
        resources :users, only: :show
        resource :user, only: :update do
          get :profile
        end
      end
    end
  end
  
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head itemtype="http://schema.org/WebSite" itemscope=""
    = viewport_meta_tag
    meta charset="utf-8"/
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/
    meta name="google-site-verification" content="bZy1hUHwYCR1jasFz-tOXC0oPPX65TADe1phMtvjomQ"/
    meta content="ID" property="og:locale" /
    meta name="author" content="SIFORLAT"/
    meta content="website" property="og:type" /
    meta name="theme-color" content="#081569"/
    meta name="u2f-support" content="true"/
    meta name="hostname" content="siforlat.com"
    = display_meta_tags site: 'Siforlat'
    = display_meta_tags og: { title: :title, description: :description }
    = yield :meta_tags
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all"
    link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous"
    / link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet"
    = favicon_link_tag 'siforlat-icon.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144'
    = favicon_link_tag 'siforlat-icon.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114'
    = favicon_link_tag 'siforlat-icon.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72'
    = favicon_link_tag 'siforlat-icon.png', rel: 'apple-touch-icon-precomposed', type: 'image/png'
    = favicon_link_tag 'siforlat-icon.png', rel: 'shortcut icon'
    script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-130269337-1"
    = javascript_include_tag "application"
    = yield :custom_library

  body.white-content
    nav#sidenav-main.navbar.navbar-vertical.fixed-left.navbar-expand-md.navbar-light.bg-white
      .container-fluid
        /! Toggler
        button.navbar-toggler aria-controls="sidenav-main" aria-expanded="false" aria-label=("Toggle navigation") data-target="#sidenav-collapse-main" data-toggle="collapse" type="button" 
          span.navbar-toggler-icon
        /! Brand
        = link_to root_path, class: "navbar-brand pt-0", data: {turbolinks: false} do
          img.navbar-brand-img alt="Sistem Informasi Jadwal Sholat" src="https://res.cloudinary.com/muhammadyana/image/upload/v1543590364/siforlat/siforlat-logo-black.png" /
        /! User
        ul.nav.align-items-center.d-md-none
          li.nav-item.dropdown
            a.nav-link.nav-link-icon aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
              i.ni.ni-bell-55
            .dropdown-menu.dropdown-menu-arrow.dropdown-menu-right aria-labelledby="navbar-default_dropdown_1" 
              a.dropdown-item href="#"  Action
              a.dropdown-item href="#"  Another action
              .dropdown-divider
              a.dropdown-item href="#"  Something else here
          li.nav-item.dropdown
            a.nav-link aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
              .media.align-items-center
                span.avatar.avatar-sm.rounded-circle
                  = gravatar_for(current_user)
                  / img alt=("Image placeholder") src="https://res.cloudinary.com/muhammadyana/image/upload/v1543153812/siforlat/siforlat-icon.png" /
            .dropdown-menu.dropdown-menu-arrow.dropdown-menu-right
              .dropdown-header.noti-title
                h6.text-overflow.m-0 Welcome!
              a.dropdown-item href="#" 
                i.ni.ni-single-02
                span My profile
              a.dropdown-item href="#" 
                i.ni.ni-settings-gear-65
                span Settings
              /a.dropdown-item href="../examples/profile.html" 
                i.ni.ni-calendar-grid-58
                span Activity
              /a.dropdown-item href="../examples/profile.html" 
                i.ni.ni-support-16
                span Support
              .dropdown-divider
              a.dropdown-item href="#!" 
                i.ni.ni-user-run
                span Logout
        /! Collapse
        #sidenav-collapse-main.collapse.navbar-collapse
          /! Collapse header
          .navbar-collapse-header.d-md-none
            .row
              .col-6.collapse-brand
                = link_to dashboard_path do
                  img src="https://res.cloudinary.com/muhammadyana/image/upload/v1543590364/siforlat/siforlat-logo-black.png" /
              .col-6.collapse-close
                button.navbar-toggler aria-controls="sidenav-main" aria-expanded="false" aria-label=("Toggle sidenav") data-target="#sidenav-collapse-main" data-toggle="collapse" type="button" 
                  span
                  span
          /! Form
          form.mt-4.mb-3.d-md-none
            .input-group.input-group-rounded.input-group-merge
              input.form-control.form-control-rounded.form-control-prepended aria-label="Search" placeholder="Search" type="search" /
              .input-group-prepend
                .input-group-text
                  span.fa.fa-search
          /! Navigation
          ul.navbar-nav
            li.nav-item
              = link_to dashboard_path, class: "nav-link" do
                i.ni.ni-tv-2.text-primary
                | Dashboard
            li.nav-item
              = link_to mosques_path, class: 'nav-link', data: {turbolinks: false} do
                i.ni.ni-istanbul.text-success
                | All Mosques
            / li.nav-item
            /   a.nav-link href="../examples/maps.html" 
            /     i.ni.ni-pin-3.text-orange
            /     | Maps
            / li.nav-item
            /   a.nav-link.active href="../examples/profile.html" 
            /     i.ni.ni-single-02.text-yellow
            /     | User profile
            / li.nav-item
            /   a.nav-link href="../examples/tables.html" 
            /     i.ni.ni-bullet-list-67.text-red
            /     | Tables
            / li.nav-item
            /   a.nav-link href="../examples/login.html" 
            /     i.ni.ni-key-25.text-info
            /     | Login
            / li.nav-item
            /   a.nav-link href="../examples/register.html" 
            /     i.ni.ni-circle-08.text-pink
            /     | Register
          /! Divider
          hr.my-3/
          /! Heading
          / h6.navbar-heading.text-muted Documentation
          / /! Navigation
          / ul.navbar-nav.mb-md-3
          /   li.nav-item
          /     a.nav-link href="https://demos.creative-tim.com/argon-dashboard/docs/getting-started/overview.html" 
          /       i.ni.ni-spaceship
          /       | Getting started
          /   li.nav-item
          /     a.nav-link href="https://demos.creative-tim.com/argon-dashboard/docs/foundation/colors.html" 
          /       i.ni.ni-palette
          /       | Foundation
          /   li.nav-item
          /     a.nav-link href="https://demos.creative-tim.com/argon-dashboard/docs/components/alerts.html" 
          /       i.ni.ni-ui-04
          /       | Components
    .main-content
      / top navbar
      nav#navbar-main.navbar.navbar-top.navbar-expand-md.navbar-dark
        .container-fluid
          /! Brand
          = link_to current_user.mosque.name, user_mosque_path(current_user, current_user.mosque), class: "h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" if current_user.mosque.present?
          
          /! Form
          /form.navbar-search.navbar-search-dark.form-inline.mr-3.d-none.d-md-flex.ml-lg-auto
            .form-group.mb-0
              .input-group.input-group-alternative
                .input-group-prepend
                  span.input-group-text
                    i.fas.fa-search
                input.form-control placeholder="Search" type="text" /
          /! User
          ul.navbar-nav.align-items-center.d-none.d-md-flex
            li.nav-item.dropdown
              a.nav-link.pr-0 aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
                .media.align-items-center
                  span.avatar.avatar-sm.rounded-circle
                    = gravatar_for(current_user)
                    / img alt=("Image placeholder") src="https://res.cloudinary.com/muhammadyana/image/upload/v1543153812/siforlat/siforlat-icon.png" /
                  .media-body.ml-2.d-none.d-lg-block
                    span.mb-0.text-sm.font-weight-bold = current_user.full_name
                .dropdown-menu.dropdown-menu-arrow.dropdown-menu-right
                  .dropdown-header.noti-title
                    h6.text-overflow.m-0 Welcome!
                  a.dropdown-item href="#" 
                    i.ni.ni-single-02
                    span My profile
                  a.dropdown-item href="#" 
                    i.ni.ni-settings-gear-65
                    span Settings
                  a.dropdown-item href="#" 
                    i.ni.ni-calendar-grid-58
                    span Activity
                  a.dropdown-item href="#" 
                    i.ni.ni-support-16
                    span Support
                  .dropdown-divider
                  - if user_signed_in?
                    = link_to logout_path, method: :delete, class: "dropdown-item"
                      i.ni.ni-user-run
                      span Logout
      = yield
      /! Footer
      .container-fluid
        footer.footer
          .row.align-items-center.justify-content-xl-between
            .col-xl-6
              .copyright.text-center.text-xl-left.text-muted
                | &copy; 2018
                a.font-weight-bold.ml-1 href="#" target="_blank"  Siforlat - Sistem Informasi Jadwal Sholat
    
    = yield :js_plugin
  - if notice
    javascript:
      notie.alert({
        type: 1, // optional, default = 4, enum: [1, 2, 3, 4, 5, 'success', 'warning', 'error', 'info', 'neutral']
        text: "#{notice}",
        stay: false, // optional, default = false
        time: 4, // optional, default = 3, minimum = 1,
        position: 'top' // optional, default = 'top', enum: ['top', 'bottom']
      });
  - if alert
    javascript:
      notie.alert({
        type: 2, // optional, default = 4, enum: [1, 2, 3, 4, 5, 'success', 'warning', 'error', 'info', 'neutral']
        text: "#{alert}",
        stay: false, // optional, default = false
        time: 4, // optional, default = 3, minimum = 1,
        position: 'top' // optional, default = 'top', enum: ['top', 'bottom']
      });

app/views/layouts/authentication.html.slim
doctype html
html lang="en"
  head itemtype="http://schema.org/WebSite" itemscope=""
    meta charset="utf-8"/
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/
    meta name="google-site-verification" content="bZy1hUHwYCR1jasFz-tOXC0oPPX65TADe1phMtvjomQ"/
    meta content="ID" property="og:locale" /
    meta name="author" content="SIFORLAT"/
    meta content="website" property="og:type" /
    meta name="theme-color" content="#081569"/
    meta name="u2f-support" content="true"/
    meta name="hostname" content="siforlat.com"
    = display_meta_tags site: 'Siforlat'
    = display_meta_tags og: { title: :title, description: :description }
    = yield :meta_tags
    = csrf_meta_tags

    = stylesheet_link_tag "application", media: "all"
    / link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet"
    = favicon_link_tag 'siforlat-icon.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144'
    = favicon_link_tag 'siforlat-icon.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114'
    = favicon_link_tag 'siforlat-icon.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72'
    = favicon_link_tag 'siforlat-icon.png', rel: 'apple-touch-icon-precomposed', type: 'image/png'
    = favicon_link_tag 'siforlat-icon.png', rel: 'shortcut icon'
    script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-130269337-1"
    = javascript_include_tag "application"

  body.bg-default
    .main-content
      / nav.navbar.navbar-top.navbar-horizontal.navbar-expand-md.navbar-dark
        .container.px-4
          a.navbar-brand href="../index.html" 
            img src="https://demos.creative-tim.com/argon-dashboard/assets/img/brand/white.png" /
          button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbar-collapse-main" data-toggle="collapse" type="button" 
            span.navbar-toggler-icon
          #navbar-collapse-main.collapse.navbar-collapse
            /! Collapse header
            .navbar-collapse-header.d-md-none
              .row
                .col-6.collapse-brand
                  a href="../index.html" 
                    img src="https://demos.creative-tim.com/argon-dashboard/assets/img/brand/blue.png" /
                .col-6.collapse-close
                  button.navbar-toggler aria-controls="sidenav-main" aria-expanded="false" aria-label=("Toggle sidenav") data-target="#navbar-collapse-main" data-toggle="collapse" type="button" 
                    span
                    span
            /! Navbar items
            ul.navbar-nav.ml-auto
              li.nav-item
                a.nav-link.nav-link-icon href="../index.html" 
                  i.ni.ni-planet
                  span.nav-link-inner--text Dashboard
              li.nav-item
                a.nav-link.nav-link-icon href="../examples/register.html" 
                  i.ni.ni-circle-08
                  span.nav-link-inner--text Register
              li.nav-item
                a.nav-link.nav-link-icon href="../examples/login.html" 
                  i.ni.ni-key-25
                  span.nav-link-inner--text Login
              li.nav-item
                a.nav-link.nav-link-icon href="../examples/profile.html" 
                  i.ni.ni-single-02
                  span.nav-link-inner--text Profile

      = yield

    / footer.py-5
      .container
        .row.align-items-center.justify-content-xl-between
          .col-xl-6
            .copyright.text-center.text-xl-left.text-muted
              | \&copy; 2018
              a.font-weight-bold.ml-1 href="https://www.creative-tim.com" target="_blank"  Creative Tim
          .col-xl-6
            ul.nav.nav-footer.justify-content-center.justify-content-xl-end
              li.nav-item
                a.nav-link href="https://www.creative-tim.com" target="_blank"  Creative Tim
              li.nav-item
                a.nav-link href="https://www.creative-tim.com/presentation" target="_blank"  About Us
              li.nav-item
                a.nav-link href="http://blog.creative-tim.com" target="_blank"  Blog
              li.nav-item
                a.nav-link href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" target="_blank"  MIT License

        
   
    = yield :js_plugin
  - if notice
    javascript:
      notie.alert({
        type: 1, // optional, default = 4, enum: [1, 2, 3, 4, 5, 'success', 'warning', 'error', 'info', 'neutral']
        text: "#{notice}",
        stay: false, // optional, default = false
        time: 4, // optional, default = 3, minimum = 1,
        position: 'top' // optional, default = 'top', enum: ['top', 'bottom']
      });
  - if alert
    javascript:
      notie.alert({
        type: 2, // optional, default = 4, enum: [1, 2, 3, 4, 5, 'success', 'warning', 'error', 'info', 'neutral']
        text: "#{alert}",
        stay: false, // optional, default = false
        time: 4, // optional, default = 3, minimum = 1,
        position: 'top' // optional, default = 'top', enum: ['top', 'bottom']
      });
      
    

app/views/layouts/landing.html.slim
doctype html
html lang="en"
  head itemtype="http://schema.org/WebSite" itemscope=""
    = viewport_meta_tag
    meta charset="utf-8"/
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/
    meta name="google-site-verification" content="bZy1hUHwYCR1jasFz-tOXC0oPPX65TADe1phMtvjomQ"/
    meta content="ID" property="og:locale" /
    meta name="author" content="SIFORLAT"/
    meta content="website" property="og:type" /
    meta name="theme-color" content="#081569"/
    meta name="u2f-support" content="true"/
    meta name="hostname" content="siforlat.com"
    = display_meta_tags site: 'Siforlat'
    = display_meta_tags og: { title: :title, description: :description }
    = yield :meta_tags
    = csrf_meta_tags

    = stylesheet_link_tag "landing", media: "all"
    / link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet"
    = favicon_link_tag 'siforlat-icon.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144'
    = favicon_link_tag 'siforlat-icon.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114'
    = favicon_link_tag 'siforlat-icon.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72'
    = favicon_link_tag 'siforlat-icon.png', rel: 'apple-touch-icon-precomposed', type: 'image/png'
    = favicon_link_tag 'siforlat-icon.png', rel: 'shortcut icon'
    script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-130269337-1"
    = javascript_include_tag "landing"



  body
    header.header-global
      nav#navbar-main.navbar.navbar-main.navbar-expand-lg.navbar-transparent.navbar-light.headroom
        .container
          = link_to root_path, class: "navbar-brand mr-lg-5", data: {turbolinks: false} do
            img src="https://res.cloudinary.com/muhammadyana/image/upload/v1543342447/siforlat/SIFORLAT-LOGO.png" /
          button.navbar-toggler aria-controls="navbar_global" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbar_global" data-toggle="collapse" type="button" 
            span.navbar-toggler-icon
          #navbar_global.navbar-collapse.collapse
            .navbar-collapse-header
              .row
                .col-6.collapse-brand
                  = link_to root_path, class: "navbar-brand mr-lg-5" do
                    img src="https://res.cloudinary.com/muhammadyana/image/upload/v1543590364/siforlat/siforlat-logo-black.png" /
                  
                .col-6.collapse-close
                  button.navbar-toggler aria-controls="navbar_global" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbar_global" data-toggle="collapse" type="button" 
                    span
                    span
            ul.navbar-nav.navbar-nav-hover.align-items-lg-center
              /li.nav-item.dropdown
                a.nav-link data-toggle="dropdown" href="#" role="button" 
                  i.ni.ni-ui-04.d-lg-none
                  span.nav-link-inner--text Components
                .dropdown-menu.dropdown-menu-xl
                  .dropdown-menu-inner
                    a.media.d-flex.align-items-center href="https://demos.creative-tim.com/argon-design-system/docs/getting-started/overview.html" 
                      .icon.icon-shape.bg-gradient-primary.rounded-circle.text-white
                        i.ni.ni-spaceship
                      .media-body.ml-3
                        h6.heading.text-primary.mb-md-1 Getting started
                        p.description.d-none.d-md-inline-block.mb-0 Learn how to use Argon compiling Scss, change brand colors and more.
                    a.media.d-flex.align-items-center href="https://demos.creative-tim.com/argon-design-system/docs/foundation/colors.html" 
                      .icon.icon-shape.bg-gradient-success.rounded-circle.text-white
                        i.ni.ni-palette
                      .media-body.ml-3
                        h6.heading.text-primary.mb-md-1 Foundation
                        p.description.d-none.d-md-inline-block.mb-0 Learn more about colors, typography, icons and the grid system we used for Argon.
                    a.media.d-flex.align-items-center href="https://demos.creative-tim.com/argon-design-system/docs/components/alerts.html" 
                      .icon.icon-shape.bg-gradient-warning.rounded-circle.text-white
                        i.ni.ni-ui-04
                      .media-body.ml-3
                        h5.heading.text-warning.mb-md-1 Components
                        p.description.d-none.d-md-inline-block.mb-0 Browse our 50 beautiful handcrafted components offered in the Free version.
              li.nav-item.dropdown
                a.nav-link data-toggle="dropdown" href="#" role="button" 
                  i.ni.ni-collection.d-lg-none
                  span.nav-link-inner--text API
                .dropdown-menu
                  a.dropdown-item target="_blank" href="http://api.siforlat.com"  API Source Code
                  a.dropdown-item target="_blank" href="https://siforlat.docs.stoplight.io/"  API Documentation
                  
                  
            ul.navbar-nav.align-items-lg-center.ml-lg-auto
              / li.nav-item
                a.nav-link.nav-link-icon data-toggle="tooltip" href="#" target="_blank" title=("Like us on Facebook") 
                  i.fa.fa-facebook-square
                  span.nav-link-inner--text.d-lg-none Facebook
              / li.nav-item
                a.nav-link.nav-link-icon data-toggle="tooltip" href="#" target="_blank" title=("Follow us on Instagram") 
                  i.fa.fa-instagram
                  span.nav-link-inner--text.d-lg-none Instagram
              / li.nav-item
                a.nav-link.nav-link-icon data-toggle="tooltip" href="#" target="_blank" title=("Follow us on Twitter") 
                  i.fa.fa-twitter-square
                  span.nav-link-inner--text.d-lg-none Twitter
              li.nav-item
                a.nav-link.nav-link-icon data-toggle="tooltip" href="https://github.com/muhammadyana/sistem-informasi-jadwal-sholat-siforlat" target="_blank" title=("Star us on Github") 
                  i.fa.fa-github
                  span.nav-link-inner--text.d-lg-none Github
              li.nav-item.d-lg-block.ml-lg-4
                - if user_signed_in?
                  = link_to logout_path, method: :delete, class: "btn btn-warning btn-icon" do
                    span.nav-link-inner--text Logout
                  = link_to dashboard_path, class: "btn btn-info btn-icon" do
                    span.nav-link-inner--text Dashboard
                - else
                  = link_to new_user_session_path, class: "btn btn-neutral btn-icon" do
                    span.nav-link-inner--text Login

    main
      = yield
    = yield :js_plugin
  - if notice
    javascript:
      notie.alert({
        type: 1, // optional, default = 4, enum: [1, 2, 3, 4, 5, 'success', 'warning', 'error', 'info', 'neutral']
        text: "#{notice}",
        stay: false, // optional, default = false
        time: 4, // optional, default = 3, minimum = 1,
        position: 'top' // optional, default = 'top', enum: ['top', 'bottom']
      });
  - if alert
    javascript:
      notie.alert({
        type: 2, // optional, default = 4, enum: [1, 2, 3, 4, 5, 'success', 'warning', 'error', 'info', 'neutral']
        text: "#{alert}",
        stay: false, // optional, default = false
        time: 4, // optional, default = 3, minimum = 1,
        position: 'top' // optional, default = 'top', enum: ['top', 'bottom']
      });